export const testData = {
  listenerNameString: "Listener: Malekith the Accursed",
  listenerName: "Malekith the Accursed",
  damageTo: "[ 2025.11.10 16:17:44 ] (combat) <color=0xff00ffff><b>29</b> <color=0x77ffffff><font size=10>to</font> <b><color=0xffffffff>Malekith the Accursed[TRY1N](Dramiel)</b><font size=10><color=0x77ffffff> - Imperial Navy Acolyte - Penetrates",
  damageFrom: "[ 2025.11.09 17:46:26 ] (combat) <color=0xffcc0000><b>61</b> <color=0x77ffffff><font size=10>from</font> <b><color=0xffffffff>Skithblatnir[GENOS](Zarmazd)</b><font size=10><color=0x77ffffff> - Dark Blood Small EMP Smartbomb - Hits",
  repairFrom: "[ 2025.11.09 17:46:22 ] (combat) <color=0xffccff66><b>0</b><color=0x77ffffff><font size=10> remote armor repaired by </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Heavy Armor Maintenance Bot II</b></u></color></font><font size=12><color=0xFFFEFF6F> [<b>HYDRA</b>]</color></font> [<b>GENOS</b>] [Heavy Armor Maintenance Bot II]<color=0xFFFFFFFF><b> -</b><color=0x77ffffff><font size=10> - Heavy Armor Maintenance Bot II</font>",
  repairTo: "[ 2025.11.09 17:43:48 ] (combat) <color=0xffccff66><b>0</b><color=0x77ffffff><font size=10> remote armor repaired to </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Nightmare</b></u></color></font><font size=12><color=0xFFFEFF6F> [<b>HYDRA</b>]</color></font> [<b>GENOS</b>] [scubather]<color=0xFFFFFFFF><b> -</b><color=0x77ffffff><font size=10> - Perun Heavy Mutadaptive Remote Armor Repairer</font>",
  boostedBy: "[ 2025.11.10 00:33:08 ] (combat) <color=0xffccff66><b>123</b><color=0x77ffffff><font size=10> remote shield boosted by </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Scimitar</b></u></color></font> [Skithblatnir]<color=0xFFFFFFFF><b> - [<b>GENOS</b>]</b><color=0x77ffffff><font size=10> - Large Remote Shield Booster II</font>",
  boostedTo: "[ 2025.11.10 00:33:08 ] (combat) <color=0xffccff66><b>57</b><color=0x77ffffff><font size=10> remote shield boosted to </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Bifrost</b></u></color></font> [scubather]<color=0xFFFFFFFF><b> - [<b>GENOS</b>]</b><color=0x77ffffff><font size=10> - Large Remote Shield Booster II</font>",
  neutTo: "[ 2025.11.09 17:43:51 ] (combat) <color=0xff7fffff><b>405 GJ</b><color=0x77ffffff><font size=10> energy neutralized </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Zarmazd</b></u></color></font><font size=12><color=0xFFFEFF6F> [<b>HYDRA</b>]</color></font> [<b>GENOS</b>] [Skithblatnir]<color=0xFFFFFFFF><b> -</b><color=0x77ffffff><font size=10> - Dark Blood Heavy Energy Neutralizer</font>",
  neutFrom: "[ 2025.11.09 17:43:51 ] (combat) <color=0xffe57f7f><b>405 GJ</b><color=0x77ffffff><font size=10> energy neutralized </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Nightmare</b></u></color></font><font size=12><color=0xFFFEFF6F> [<b>HYDRA</b>]</color></font> [<b>GENOS</b>] [scubather]<color=0xFFFFFFFF><b> -</b><color=0x77ffffff><font size=10> - Dark Blood Heavy Energy Neutralizer</font>",
  capTransferTo: "[ 2025.11.10 16:18:10 ] (combat) <color=0xffccff66><b>550</b><color=0x77ffffff><font size=10> remote capacitor transmitted to </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Dramiel</b></u></color></font> [Malekith the Accursed]<color=0xFFFFFFFF><b> - [<b>TRY1N</b>]</b><color=0x77ffffff><font size=10> - Centum A-Type Medium Remote Capacitor Transmitter</font>",
  capTransferFor: "[ 2025.11.10 16:18:10 ] (combat) <color=0xffccff66><b>10</b><color=0x77ffffff><font size=10> remote capacitor transmitted by </font><b><color=0xffffffff><font size=12><color=0xFFFFB900> <u><b>Guardian</b></u></color></font><font size=12><color=0xFFFEFF6F> [<b>HYDRA</b>]</color></font> [<b>GENOS</b>] [scubather]<color=0xFFFFFFFF><b> -</b><color=0x77ffffff><font size=10> - Centum A-Type Medium Remote Capacitor Transmitter</font>"

}
